name: CMake

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-project:
    runs-on: macos-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v3
      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          logfile: ${{ github.workspace }}/Build/compile_commands.json
      - uses: actions/upload-artifact@v2
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}
      - name: "Code Checker Satisfied"
        if: ${{ steps.codechecker.outputs.warnings == 'true' }}
        run: exit 1
      - name: run-cmake
        # You may pin to the exact commit or the version.
        # uses: lukka/run-cmake@2d1ee0acb9c4f656ec9128fc7387d82ac4539816
        uses: threeal/cmake-action@latest
        with:
            source-dir: ${{ github.workspace }}/Team22/Code22
            generator: Ninja
            cxx-compiler: clang++
            cxx-flags: -std=c++17
      - name: python setup
        uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.8' 
      - name: run tests
        run: python run_tests.py
